version: '1.0'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: festibuy-postgres
    environment:
      POSTGRES_DB: festibuy_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: festibuy123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: