services:
  postgres-db:
    image: postgis/postgis:16-3.4
    container_name: festibuy-postgres
    environment:
      POSTGRES_DB: festibuy_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: festibuy123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  pgdata:
    driver: local